### ISSUE TITLE
[meta] syntax for grant/revoke

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#147]
Proposed syntax:

* `please grant user jclark role admin`
* `please grant user jclark permission *.*.*` (future)
* `please grant role admin permission *.*.*`
* `please revoke user jclark role admin`
* `please revoke user jclark permission *.*.*` (future)
* `please revoke role admin permission *.*.*`

This means that you can grant someone permissions to grant a specific user permissions via `grant.user.jclark` or to just grant user permissions via `grant.user.*` or just grant via `grant.*.*` (Same for revoke). You can also allow people to manage certain roles via `grant.role.my-role`

Also, I'm thinking we should use `.` as the separator since that is not allowed in ids via the config repo rules (splits on `.`)

**Comment by jonnymbgood** [comment]
@thuey Thoughts

**Comment by thuey** [comment]
My initial thoughts are that I like it, but I'll need to think it over. A few questions:

1. Will this granting syntax only be used for granting permissions to grant other permissions?
1. If it will be used for others, then would we in practice allow `*`? Is that essentially granting a user all permissions? 
1. Just a thought, but what are your thoughts on this alternative approach?
`please grant user jclark permission "grant role my-role"`
So we would have spaces instead of `.`, which would better match up with how the permission is actually used. We would then use `"` to denote that everything between the `"` is a single argument/id.

**Comment by jonnymbgood** [comment]
1. No, it would be used for all permissions (i.e. grant role dev permission "check kubernetes prod")
2. `"* * *"` would be all permissions, yes
3. I like it, especially since `*` would be expanded outside quotes in a cli setting. Essentially `"a b *"` turns into a single arg when it's in quotes in a terminal

**Comment by jonnymbgood** [comment]
@thuey Can/should we finalize the "a b c" syntax?

**Comment by thuey** [comment]
@jclark. Let's do it

**Comment by jonnymbgood** [comment]
👍
