### ISSUE TITLE
[meta] plural or singular for config folders

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#163]
```
checks
credentials
logins
roles
users
```
vs
```
check
credential
login
role
user
```
@thuey Thoughts?

**Comment by thuey** [comment]
I would say plural. I have found plural folder names makes code more readable. Although maybe that's mostly based on my experience with JavaScript where you can have a `roles/index.js` file and then `const roles = require("./roles")`. In any case, I do think it's nice to reserve the singular form for when you have an instance, instead of a collection

**Comment by jonnymbgood** [comment]
Makes sense. Plural it is.
