### ISSUE TITLE
[meta] add random slug on the end of /slack and /cli

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#169]
@thuey Do you think it would be worth obfuscating the slack and cli endpoints with a configurable slug (specified in pleaseops.yaml in the config)?

**Comment by thuey** [comment]
I'm assuming instead of "work" you meant "worth." I could think of two reasons why you might be proposing that:

1. For security, to make it more difficult for a hacker to mess with.
Response: I'm not a huge fan of security through obscurity.
2. To communicate that customers/customers employees should not be coding stuff against the API.
Response: If you build it and hide it, they will still come.

Is there another reason, or maybe I'm oversimplifying it?

**Comment by jonnymbgood** [comment]
I only wondered because I read about people recommending using a random slug in an article (that I can't find now). As long as we can lock it down appropriately, I'm good just keeping things the way they are.
