### ISSUE TITLE
[server] error when deleting a role still in use

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#201]
When a role is deleted that is still in use, we should warn?/error?

@thuey Thoughts on warning vs error?

**Comment by jonnymbgood** [comment]
Note that we currently check for a valid role before revoking it. We should change that behavior as part of this issue.

**Comment by thuey** [comment]
What are your thoughts on a "force" flag in general? Something like please
force delete role dev

I feel like something to that effect is the best user experience, rather
than having the user go through and manually clean out wherever the role is
used.

Alternatively, we could just do it and tell them what happened. Since
everything is backed by git, it shouldn't be hard for them to revert their
change if they made a mistske

**Comment by jonnymbgood** [comment]
I'm kind of split on the concept of a flag, but imo if we do one we should probably put it on the end of the command `please delete role foo --force` or something. I'll think about this over the weekend.

Another thing to note is that there is nothing preventing them from editing the repo directly and deleting the file (which would create orphaned references). We should probably plan for the orphaned case either way.

**Comment by jonnymbgood** [comment]
For now we will error via the command.
